site_name: 'Hanfor Docs'
repo_url: 'https://github.com/ultimate-pa/hanfor'
repo_name: 'ultimate-pa/hanfor'
site_url: 'https://ultimate-pa.github.io/hanfor/'
edit_uri: 'edit/master/documentation/docs'
use_directory_urls: false

theme:
  name: 'material'
  font: false
  custom_dir: 'overrides'
  features:
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - search.share

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - attr_list
  - extra
  - figureAltCaption
  - footnotes
  - markdown_include.include:
      base_path: docs
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
  - sane_lists
  - toc:
      toc_depth: 2
      permalink: ' #'
  #- mdlightbox
  
plugins:
  - awesome-pages
  - search

