site_name: 'Hanfor Docs'
repo_url: 'https://github.com/ultimate-pa/hanfor'
site_url: 'https://ultimate-pa.github.io/hanfor/'
edit_uri: 'edit/master/documentation/docs'
repo_name: 'GitHub'
theme:
  name: 'rtd-dropdown'
  custom_dir: custom_theme/
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: ' #'
  - sane_lists
nav:
  - Introduction:
      - 'What is Hanfor?': 'index.md'
  - Installation:
      - 'Preliminaries': 'installation/preliminaries.md'
      - 'Configuration': 'installation/configuration.md'
      - 'Deployment': 'installation/deployment.md'
  - Usage:
      - 'API Queries': 'usage/api_queries.md'
      - 'FAQ': 'usage/faq.md'
      - 'Requirements': 'usage/requirements.md'
  - Contribute:
      - 'To Hanfor': 'contribute/to_hanfor.md'
      - 'To Docs': 'contribute/to_docs.md'
