site_name: 'Hanfor Docs'
repo_url: 'https://github.com/ultimate-pa/hanfor'
site_url: 'https://ultimate-pa.github.io/hanfor/'
edit_uri: 'edit/master/documentation/docs'
repo_name: 'GitHub'
theme:
  name: 'rtd-dropdown'
  custom_dir: custom_theme/
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: ' #'
      toc_depth: 2
  - sane_lists