site_name: 'Hanfor Docs'
repo_url: 'https://github.com/ultimate-pa/hanfor'
repo_name: 'ultimate-pa/hanfor'
site_url: 'https://ultimate-pa.github.io/hanfor/'
edit_uri: 'edit/master/documentation/docs'
use_directory_urls: false

theme:
  name: 'material'
  features:
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - search.share

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      toc_depth: 2
      permalink: ' #'
  - admonition
  - attr_list
  - footnotes
  - meta
  - sane_lists
  - figureAltCaption
  #- mdlightbox
  - extra

plugins:
  - awesome-pages
  - search

